theme: jekyll-theme-minimal
title: "VSCO Downloader by Micha Birklbauer"
description: "Project Website for VSCO Downloader"
logo: https://raw.githubusercontent.com/michabirklbauer/projects/master/avatar.jpg
show_downloads: "true"
github:
  zip_url: https://github.com/michabirklbauer/vsco_downloader/archive/master.zip
  tar_url: https://github.com/michabirklbauer/vsco_downloader/archive/master.tar.gz
